apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: librechat-ingress
  namespace: librechat
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: HTTP
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: http
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: arn:aws:acm:us-east-1:281355808288:certificate/c10d3c7e-c19c-4ed7-89c8-106a33b2a80c
    service.beta.kubernetes.io/aws-load-balancer-ssl-ports: https
spec:
  ingressClassName: nginx
  rules:
  - host: librechat.rynotrax.com
    http:
      paths:
      - backend:
          service:
            name: analytics-dashboard
            port:
              number: 80
        path: /analytics
        pathType: Prefix
      - backend:
          service:
            name: librechat
            port:
              number: 80
        path: /
        pathType: Prefix
